In [1]:
using Statistics
using DelimitedFiles

In [10]:
M = readdlm("wdbc.txt", ',')

569×32 Array{Float64,2}:
 842302.0        0.0  17.99   10.38  …  0.7119  0.2654   0.4601  0.1189
 842517.0        0.0  20.57   17.77     0.2416  0.186    0.275   0.08902
      8.43009e7  0.0  19.69   21.25     0.4504  0.243    0.3613  0.08758
      8.43483e7  0.0  11.42   20.38     0.6869  0.2575   0.6638  0.173
      8.43584e7  0.0  20.29   14.34     0.4     0.1625   0.2364  0.07678
 843786.0        0.0  12.45   15.7   …  0.5355  0.1741   0.3985  0.1244
 844359.0        0.0  18.25   19.98     0.3784  0.1932   0.3063  0.08368
      8.44582e7  0.0  13.71   20.83     0.2678  0.1556   0.3196  0.1151
 844981.0        0.0  13.0    21.82     0.539   0.206    0.4378  0.1072
      8.4501e7   0.0  12.46   24.04     1.105   0.221    0.4366  0.2075
 845636.0        0.0  16.02   23.24  …  0.1459  0.09975  0.2948  0.08452
      8.461e7    0.0  15.78   17.89     0.3965  0.181    0.3792  0.1048
 846226.0        0.0  19.17   24.8      0.3639  0.1767   0.3176  0.1023
      ⋮                            

In [11]:
y = Int.(M[:,2] .+1)

569-element Array{Int64,1}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 2
 2
 2
 2
 2
 1
 1
 1
 1
 1
 1
 2

In [12]:
X = M[:, 3:12]

569×10 Array{Float64,2}:
 17.99   10.38  122.8   1001.0  0.1184   …  0.3001   0.1471   0.2419  0.07871
 20.57   17.77  132.9   1326.0  0.08474     0.0869   0.07017  0.1812  0.05667
 19.69   21.25  130.0   1203.0  0.1096      0.1974   0.1279   0.2069  0.05999
 11.42   20.38   77.58   386.1  0.1425      0.2414   0.1052   0.2597  0.09744
 20.29   14.34  135.1   1297.0  0.1003      0.198    0.1043   0.1809  0.05883
 12.45   15.7    82.57   477.1  0.1278   …  0.1578   0.08089  0.2087  0.07613
 18.25   19.98  119.6   1040.0  0.09463     0.1127   0.074    0.1794  0.05742
 13.71   20.83   90.2    577.9  0.1189      0.09366  0.05985  0.2196  0.07451
 13.0    21.82   87.5    519.8  0.1273      0.1859   0.09353  0.235   0.07389
 12.46   24.04   83.97   475.9  0.1186      0.2273   0.08543  0.203   0.08243
 16.02   23.24  102.7    797.8  0.08206  …  0.03299  0.03323  0.1528  0.05697
 15.78   17.89  103.6    781.0  0.0971      0.09954  0.06606  0.1842  0.06082
 19.17   24.8   132.4   1123.0  0.0974 

In [13]:
X_1 = X[y .== 1, :]

212×10 Array{Float64,2}:
 17.99  10.38  122.8   1001.0  0.1184   …  0.3001   0.1471   0.2419  0.07871
 20.57  17.77  132.9   1326.0  0.08474     0.0869   0.07017  0.1812  0.05667
 19.69  21.25  130.0   1203.0  0.1096      0.1974   0.1279   0.2069  0.05999
 11.42  20.38   77.58   386.1  0.1425      0.2414   0.1052   0.2597  0.09744
 20.29  14.34  135.1   1297.0  0.1003      0.198    0.1043   0.1809  0.05883
 12.45  15.7    82.57   477.1  0.1278   …  0.1578   0.08089  0.2087  0.07613
 18.25  19.98  119.6   1040.0  0.09463     0.1127   0.074    0.1794  0.05742
 13.71  20.83   90.2    577.9  0.1189      0.09366  0.05985  0.2196  0.07451
 13.0   21.82   87.5    519.8  0.1273      0.1859   0.09353  0.235   0.07389
 12.46  24.04   83.97   475.9  0.1186      0.2273   0.08543  0.203   0.08243
 16.02  23.24  102.7    797.8  0.08206  …  0.03299  0.03323  0.1528  0.05697
 15.78  17.89  103.6    781.0  0.0971      0.09954  0.06606  0.1842  0.06082
 19.17  24.8   132.4   1123.0  0.0974      0.2065  

In [14]:
X_2 = X[y .== 2, :]

357×10 Array{Float64,2}:
 13.54   14.36  87.46  566.3  0.09779  …  0.06664   0.04781   0.1885  0.05766
 13.08   15.71  85.63  520.0  0.1075      0.04568   0.0311    0.1967  0.06811
  9.504  12.44  60.34  273.9  0.1024      0.02956   0.02076   0.1815  0.06905
 13.03   18.42  82.61  523.8  0.08983     0.02562   0.02923   0.1467  0.05863
  8.196  16.84  51.71  201.9  0.086       0.01588   0.005917  0.1769  0.06503
 12.05   14.63  78.04  449.3  0.1031   …  0.06592   0.02749   0.1675  0.06043
 13.49   22.3   86.91  561.0  0.08752     0.04751   0.03384   0.1809  0.05718
 11.76   21.6   74.72  427.9  0.08637     0.01657   0.01115   0.1495  0.05888
 13.64   16.34  87.21  571.8  0.07685     0.01857   0.01723   0.1353  0.05953
 11.94   18.24  75.71  437.6  0.08261     0.01972   0.01349   0.1868  0.0611
 11.52   18.75  73.34  409.0  0.09524  …  0.03036   0.02278   0.192   0.05907
 13.05   19.31  82.61  527.2  0.0806      0.000692  0.004167  0.1819  0.05501
  8.618  11.79  54.34  224.5  0.09752   

In [15]:
function train(X, y)
    N, D = size(X)
    K = length(unique(y))
    θ = zeros(K) # Prior distribution
    μ = zeros(K, D) # mean matrix
    σ = zeros(K, D) # standard deviation matrix
    for k = 1 : K
        θ[k] = sum(y .== k) / N
        X_k = X[y .== k, :]
        μ[k, :] = mean(X_k, dims=1)
        σ[k, :] = std(X_k, dims=1)
    end
    (θ, μ, σ)
end

train (generic function with 1 method)

In [16]:
θ, μ, σ = train(X, y)

([0.37258347978910367, 0.6274165202108963], [17.462830188679245 21.604905660377362 … 0.19290896226415097 0.06268009433962264; 12.146523809523813 17.914761904761903 … 0.17418599439775911 0.0628673949579832], [3.203971100779367 3.779469920776341 … 0.027638092143030174 0.007573315024808589; 1.7805116461410393 3.995124593675911 … 0.024806758206793282 0.0067473428139250636])

In [17]:
function classify(x, θ, μ, σ)
    K = length(θ)
    posterior = zeros(K)
    for k = 1 : K
        u = (x - μ[k, :]) ./ σ[k, :]
        posterior[k] = -sum(log.(σ[k, :])) - u'*u/2 + log(θ[k]) # log(likelihood) + log(prior)
    end
    argmax(posterior)
end

classify (generic function with 1 method)

In [18]:
prediction_100 = classify(X[100, :], θ, μ, σ)

2

In [19]:
function evaluate(X, y, θ, μ, σ)
    N = length(y)
    y_ = zeros(N)
    for i=1:N
        y_[i] = classify(X[i, :], θ, μ, σ)
    end
    sum(y_ .== y)/N
end

evaluate (generic function with 1 method)

In [20]:
evaluate(X, y, θ, μ, σ)

0.9138840070298769